language: go
go:
  - 1.1.1
  - 1.1
  - tip
services:
  - mysql
install: go get -v ./... && go list -f '{{.TestImports}}' | sed 's/\[//g' | sed 's/\]//g' | xargs go get
script: go test -v ./...
notifications:
  email:
    recipients:
      - toqoz403@gmail.com
    on_success: change
    on_failure: always
